public class WebflowPayload {
        public String name { get; set; }
        public String siteId { get; set; }
        public Map<String, String> data { get; set; }
        public String submittedAt { get; set; }
        public String id { get; set; }
        public String formId { get; set; }
        public String formElementId { get; set; }
        public String pageId { get; set; }
        public String publishedPath { get; set; }
        public String pageUrl { get; set; }
        public List<Object> schema { get; set; } 
    }